import type { AuthContext, Env } from '../types'
import { jsonError, jsonOk } from '../lib/response'

const SAMPLE_ITINERARY = [
  {
    id: 'it_01',
    order: 1,
    date: '2026-10-05',
    time: '09:00',
    title: '抵達成田機場',
    location: '成田機場 Terminal 1',
    map_url: 'https://maps.google.com/?q=成田機場',
    note: '領取JR PASS',
  },
  {
    id: 'it_02',
    order: 2,
    date: '2026-10-05',
    time: '14:00',
    title: '淺草寺',
    location: '淺草寺',
    map_url: 'https://maps.google.com/?q=淺草寺',
    note: '',
  },
  {
    id: 'it_03',
    order: 3,
    date: '2026-10-05',
    time: '18:30',
    title: '晚餐：雷門今半壽喜燒',
    location: '今半 雷門本店',
    map_url: 'https://maps.google.com/?q=今半雷門本店',
    note: '已訂位，18:30到',
  },
  {
    id: 'it_04',
    order: 1,
    date: '2026-10-06',
    time: '10:00',
    title: '明治神宮',
    location: '明治神宮',
    map_url: 'https://maps.google.com/?q=明治神宮',
    note: '',
  },
  {
    id: 'it_05',
    order: 2,
    date: '2026-10-06',
    time: '13:00',
    title: '原宿逛街',
    location: '竹下通',
    map_url: 'https://maps.google.com/?q=竹下通',
    note: '買朋友推薦的鬆餅',
  },
  {
    id: 'it_06',
    order: 3,
    date: '2026-10-06',
    time: '19:00',
    title: '澀谷夜景 + SKY EXPRESS',
    location: '澀谷Sky',
    map_url: 'https://maps.google.com/?q=澀谷Sky',
    note: 'KKday票券已在旅行文件',
  },
  {
    id: 'it_07',
    order: 1,
    date: '2026-10-07',
    time: '08:30',
    title: '搭新幹線前往京都',
    location: '東京車站',
    map_url: 'https://maps.google.com/?q=東京車站',
    note: '車票在旅行文件',
  },
  {
    id: 'it_08',
    order: 2,
    date: '2026-10-07',
    time: '12:00',
    title: '伏見稻荷大社',
    location: '伏見稻荷大社',
    map_url: 'https://maps.google.com/?q=伏見稻荷大社',
    note: '',
  },
  {
    id: 'it_09',
    order: 1,
    date: '2026-10-08',
    time: '09:00',
    title: '清水寺',
    location: '清水寺',
    map_url: 'https://maps.google.com/?q=清水寺',
    note: '',
  },
  {
    id: 'it_10',
    order: 2,
    date: '2026-10-08',
    time: '15:00',
    title: '祇園散策晚餐',
    location: '祇園',
    map_url: 'https://maps.google.com/?q=祇園',
    note: '找間町屋居酒屋吃晚餐',
  },
  {
    id: 'it_11',
    order: 1,
    date: '2026-10-09',
    time: '09:00',
    title: '嵐山竹林小徑',
    location: '嵐山竹林小徑',
    map_url: 'https://maps.google.com/?q=嵐山竹林小徑',
    note: '',
  },
  {
    id: 'it_12',
    order: 2,
    date: '2026-10-09',
    time: '13:00',
    title: '金閣寺',
    location: '金閣寺',
    map_url: 'https://maps.google.com/?q=金閣寺',
    note: '',
  },
  {
    id: 'it_13',
    order: 1,
    date: '2026-10-10',
    time: '09:00',
    title: '搭新幹線前往大阪',
    location: '京都車站',
    map_url: 'https://maps.google.com/?q=京都車站',
    note: '車票在旅行文件',
  },
  {
    id: 'it_14',
    order: 2,
    date: '2026-10-10',
    time: '12:00',
    title: '大阪城',
    location: '大阪城公園',
    map_url: 'https://maps.google.com/?q=大阪城公園',
    note: '',
  },
  {
    id: 'it_15',
    order: 3,
    date: '2026-10-10',
    time: '18:00',
    title: '心齋橋逛街晚餐',
    location: '心齋橋筋商店街',
    map_url: 'https://maps.google.com/?q=心齋橋筋商店街',
    note: '',
  },
  {
    id: 'it_16',
    order: 1,
    date: '2026-10-11',
    time: '09:00',
    title: '大阪環球影城',
    location: '環球影城',
    map_url: 'https://maps.google.com/?q=大阪環球影城',
    note: '已買快速通關票',
  },
  {
    id: 'it_17',
    order: 1,
    date: '2026-10-12',
    time: '09:00',
    title: '奈良公園餵鹿',
    location: '奈良公園',
    map_url: 'https://maps.google.com/?q=奈良公園',
    note: '記得買鹿仙貝',
  },
  {
    id: 'it_18',
    order: 2,
    date: '2026-10-12',
    time: '13:00',
    title: '東大寺',
    location: '東大寺',
    map_url: 'https://maps.google.com/?q=東大寺',
    note: '',
  },
  {
    id: 'it_19',
    order: 1,
    date: '2026-10-13',
    time: '10:00',
    title: '道頓堀散策',
    location: '道頓堀',
    map_url: 'https://maps.google.com/?q=道頓堀',
    note: '',
  },
  {
    id: 'it_20',
    order: 2,
    date: '2026-10-13',
    time: '15:00',
    title: '黑門市場',
    location: '黑門市場',
    map_url: 'https://maps.google.com/?q=黑門市場',
    note: '吃海鮮串燒當下午茶',
  },
  {
    id: 'it_21',
    order: 1,
    date: '2026-10-14',
    time: '08:00',
    title: '搭新幹線返回東京',
    location: '新大阪車站',
    map_url: 'https://maps.google.com/?q=新大阪車站',
    note: '車票在旅行文件',
  },
  {
    id: 'it_22',
    order: 2,
    date: '2026-10-14',
    time: '15:00',
    title: '銀座逛街',
    location: '銀座',
    map_url: 'https://maps.google.com/?q=銀座',
    note: '',
  },
  {
    id: 'it_23',
    order: 1,
    date: '2026-10-15',
    time: '10:00',
    title: '台場自由行',
    location: '台場海濱公園',
    map_url: 'https://maps.google.com/?q=台場海濱公園',
    note: '',
  },
  {
    id: 'it_24',
    order: 2,
    date: '2026-10-15',
    time: '18:30',
    title: '晚餐燒肉',
    location: '燒肉トラジ 六本木店',
    map_url: 'https://maps.google.com/?q=燒肉トラジ六本木店',
    note: '慶祝旅程最後一晚',
  },
  {
    id: 'it_25',
    order: 1,
    date: '2026-10-16',
    time: '09:00',
    title: '退房前往機場',
    location: '東京喜來登飯店',
    map_url: 'https://maps.google.com/?q=東京喜來登飯店',
    note: '',
  },
  {
    id: 'it_26',
    order: 2,
    date: '2026-10-16',
    time: '13:00',
    title: '成田機場起飛',
    location: '成田機場',
    map_url: 'https://maps.google.com/?q=成田機場',
    note: '長榮航空 check-in',
  },
]

const SAMPLE_DOCUMENTS = [
  {
    id: 'doc_01',
    order: 1,
    category: '住宿',
    title: '東京喜來登飯店',
    date_start: '2026-10-05',
    date_end: '2026-10-08',
    link: 'https://booking.com/xxx',
    note: '訂單號 BK123456，Check-in 15:00',
  },
  {
    id: 'doc_02',
    order: 2,
    category: '機票',
    title: '長榮 BR198 台北→東京',
    date_start: '2026-10-05',
    date_end: '',
    link: '',
    note: '去程 08:00起飛，訂位代號 ABC123',
  },
  {
    id: 'doc_03',
    order: 3,
    category: '簽證',
    title: '日本短期簽證',
    date_start: '',
    date_end: '',
    link: '',
    note: '免簽，護照效期需6個月以上',
  },
  {
    id: 'doc_04',
    order: 4,
    category: '票券',
    title: '澀谷Sky展望台門票',
    date_start: '2026-10-06',
    date_end: '',
    link: 'https://kkday.com/xxx',
    note: '憑QR code入場，19:00場次',
  },
  {
    id: 'doc_05',
    order: 5,
    category: '火車',
    title: '新幹線 東京→京都',
    date_start: '2026-10-07',
    date_end: '',
    link: '',
    note: '08:30發車，指定席 車廂8 座位5A',
  },
  {
    id: 'doc_06',
    order: 6,
    category: '交通',
    title: 'JR PASS 7日券',
    date_start: '2026-10-05',
    date_end: '2026-10-11',
    link: '',
    note: '成田機場領取',
  },
]

const SAMPLE_INFO = [
  {
    id: 'info_01',
    order: 1,
    category: '工具',
    title: '日圓匯率換算',
    link: 'https://www.xe.com',
    note: '',
    is_checked: false,
  },
  {
    id: 'info_02',
    order: 2,
    category: '工具',
    title: 'Google翻譯離線包',
    link: '',
    note: '出發前記得下載日文離線包',
    is_checked: true,
  },
  {
    id: 'info_03',
    order: 3,
    category: '靈感',
    title: '小紅書推薦的原宿咖啡廳',
    link: 'https://xhslink.com/xxx',
    note: '朋友說必吃鬆餅',
    is_checked: false,
  },
  {
    id: 'info_04',
    order: 4,
    category: '靈感',
    title: 'IG看到的今治毛巾專賣店',
    link: 'https://instagram.com/xxx',
    note: '銀座店',
    is_checked: false,
  },
  {
    id: 'info_05',
    order: 5,
    category: '緊急聯絡',
    title: '駐日台北經濟文化代表處',
    link: '',
    note: '電話：03-3280-7811，地址：東京都港區白金台5-20-2',
    is_checked: false,
  },
  {
    id: 'info_06',
    order: 6,
    category: '緊急聯絡',
    title: '海外突發傷病險 24hr專線',
    link: '',
    note: '電話：0800-xxx-xxx',
    is_checked: false,
  },
]

const SAMPLE_CHECKLIST = [
  {
    id: 'chk_01',
    order: 1,
    category: '證件',
    title: '護照正本',
    note: '確認效期6個月以上',
    is_checked: false,
  },
  {
    id: 'chk_02',
    order: 2,
    category: '證件',
    title: '駕照國際譯本',
    note: '',
    is_checked: false,
  },
  {
    id: 'chk_03',
    order: 3,
    category: '電子用品',
    title: '萬國轉接頭',
    note: '',
    is_checked: true,
  },
  {
    id: 'chk_04',
    order: 4,
    category: '電子用品',
    title: '行動電源',
    note: '過安檢隨身帶',
    is_checked: true,
  },
  {
    id: 'chk_05',
    order: 5,
    category: '藥品',
    title: '腸胃藥、暈車藥',
    note: '',
    is_checked: false,
  },
]

export const onRequestGet: PagesFunction<Env, any, AuthContext> = async (context) => {
  const { DB } = context.env
  const userId = context.data.userId

  try {
    const statements = [
      ...SAMPLE_ITINERARY.map((it) =>
        DB.prepare(
          `INSERT OR REPLACE INTO itinerary (id, user_id, "order", date, time, title, location, map_url, note)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        ).bind(`${userId}_${it.id}`, userId, it.order, it.date, it.time, it.title, it.location, it.map_url, it.note),
      ),
      ...SAMPLE_DOCUMENTS.map((doc) =>
        DB.prepare(
          `INSERT OR REPLACE INTO documents (id, user_id, "order", category, title, date_start, date_end, link, note)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        ).bind(`${userId}_${doc.id}`, userId, doc.order, doc.category, doc.title, doc.date_start, doc.date_end, doc.link, doc.note),
      ),
      ...SAMPLE_INFO.map((info) =>
        DB.prepare(
          `INSERT OR REPLACE INTO info (id, user_id, "order", category, title, link, note, is_checked)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        ).bind(`${userId}_${info.id}`, userId, info.order, info.category, info.title, info.link, info.note, info.is_checked ? 1 : 0),
      ),
      ...SAMPLE_CHECKLIST.map((chk) =>
        DB.prepare(
          `INSERT OR REPLACE INTO checklist (id, user_id, "order", category, title, note, is_checked)
           VALUES (?, ?, ?, ?, ?, ?, ?)`,
        ).bind(`${userId}_${chk.id}`, userId, chk.order, chk.category, chk.title, chk.note, chk.is_checked ? 1 : 0),
      ),
    ]

    await DB.batch(statements)

    return jsonOk({
      inserted: {
        itinerary: SAMPLE_ITINERARY.length,
        documents: SAMPLE_DOCUMENTS.length,
        info: SAMPLE_INFO.length,
        checklist: SAMPLE_CHECKLIST.length,
      },
    })
  } catch (err) {
    return jsonError(err instanceof Error ? err.message : 'sample insert failed', 500)
  }
}
